Update dapper build
Signed-off-by: seanly liu <seanly@opsbox.dev>

diff --git a/toolset/dapper/Dockerfile b/toolset/dapper/Dockerfile
--- a/toolset/dapper/Dockerfile
+++ b/toolset/dapper/Dockerfile
@@ -1,15 +1,25 @@
-FROM alpine
+# Build dapper
+FROM golang:1.20.5 as go-builder
 
-#RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
-RUN apk update && apk add --update --no-cache curl 
+WORKDIR /build
 
-ARG DAPPER_VERSION=v0.6.0
+# Install the dependencies
+RUN git clone -b secret https://github.com/seanly/dapper /build
+RUN go mod download
 
-RUN \
-    ( \
-    set -x; cd "$(mktemp -d)" && \
-    ARCH="$(uname -m)" && \
-    DAPPER_URL=https://github.com/rancher/dapper/releases/download/${DAPPER_VERSION}/dapper-Linux-${ARCH} && \
-    wget -O /usr/bin/dapper ${DAPPER_URL} && \
-    chmod +x /usr/bin/dapper \
-    )
+RUN set -eux \
+    ; VERSION=$(git rev-parse --short HEAD) \
+    ; OS="$(uname | tr '[:upper:]' '[:lower:]')" \
+    ; ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" \
+    ;case "$ARCH" in \
+		arm64) \
+            CGO_ENABLED=0 GOARCH=${ARCH} go build \
+                -a -tags netgo -installsuffix netgo \
+                -ldflags "-X main.VERSION=$VERSION" -o /usr/bin/dapper main.go;; \
+		amd64) \
+            CGO_ENABLED=0 GOARCH=${ARCH} go build \
+                -a -tags netgo -installsuffix netgo \
+                -ldflags "-X main.VERSION=$VERSION -extldflags '-static -s'" -o /usr/bin/dapper main.go ;;\
+		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+	esac; \
+    CGO_ENABLED=0 GOARCH=${ARCH} GOOS=darwin go build -ldflags "-X main.VERSION=$VERSION"  -o ./bin/dapper-Darwin-${ARCH} main.go
